# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_led_hello_world/design_led_hello_world.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world || ORIG_REF_NAME==design_led_hello_world}]

# IP: bd/design_led_hello_world/ip/design_led_hello_world_processing_system7_0_0/design_led_hello_world_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world_processing_system7_0_0 || ORIG_REF_NAME==design_led_hello_world_processing_system7_0_0}]

# IP: bd/design_led_hello_world/ip/design_led_hello_world_axi_gpio_0_0/design_led_hello_world_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world_axi_gpio_0_0 || ORIG_REF_NAME==design_led_hello_world_axi_gpio_0_0}]

# IP: bd/design_led_hello_world/ip/design_led_hello_world_processing_system7_0_axi_periph_0/design_led_hello_world_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_led_hello_world_processing_system7_0_axi_periph_0}]

# IP: bd/design_led_hello_world/ip/design_led_hello_world_rst_processing_system7_0_50M_0/design_led_hello_world_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==design_led_hello_world_rst_processing_system7_0_50M_0}]

# IP: bd/design_led_hello_world/ip/design_led_hello_world_auto_pc_0/design_led_hello_world_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world_auto_pc_0 || ORIG_REF_NAME==design_led_hello_world_auto_pc_0}]

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_processing_system7_0_0/design_led_hello_world_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_led_hello_world_processing_system7_0_0 || ORIG_REF_NAME==design_led_hello_world_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_axi_gpio_0_0/design_led_hello_world_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_axi_gpio_0_0/design_led_hello_world_axi_gpio_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_led_hello_world_axi_gpio_0_0 || ORIG_REF_NAME==design_led_hello_world_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_axi_gpio_0_0/design_led_hello_world_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_led_hello_world_axi_gpio_0_0 || ORIG_REF_NAME==design_led_hello_world_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_rst_processing_system7_0_50M_0/design_led_hello_world_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==design_led_hello_world_rst_processing_system7_0_50M_0}]

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_rst_processing_system7_0_50M_0/design_led_hello_world_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_rst_processing_system7_0_50M_0/design_led_hello_world_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_hello_world_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==design_led_hello_world_rst_processing_system7_0_50M_0}]

# XDC: bd/design_led_hello_world/ip/design_led_hello_world_auto_pc_0/design_led_hello_world_auto_pc_0_ooc.xdc

# XDC: bd/design_led_hello_world/design_led_hello_world_ooc.xdc
